const express = require('express')
const router = express.Router()

const clientRoutes = require('./clientRoutes')
const partnerRoutes = require('./partnerRoutes')
const adminRoutes = require('./adminRoutes')
const commonRoutes = require('./common')
const staticRoutes = require('./staticRoutes')
const eventsRoutes = require('./eventsRoutes')
const autreRoutes = require('./autreRoutes')
const initHelper = require('../controllers/initHelper')

router.use('/client', clientRoutes)
router.use('/partner', partnerRoutes)
router.use('/admin', adminRoutes)
router.use('/common', commonRoutes)
router.use('/statistic', staticRoutes)
router.use('/', eventsRoutes)
router.use('/autre', autreRoutes)
router.post('/initwilaya', initHelper.add58wilaya)
module.exports = router
